name: "nsfw"
platform: "pytorch_libtorch"
max_batch_size: 0

input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 224, 224]
  }
]

output [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [2]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

# dynamic_batching removed because the model returns a fixed batch size (1)
